export { default as Heading } from './heading'
export { default as Text } from './text'
export { default as ThemeToggle } from './theme-toggle'
export { default as ContactForm } from './contact-form'
export { default as Footer } from './footer'
export { default as SEO } from './seo'
